apiVersion: v1
kind: Service
metadata:
  name: frontend-todo
  namespace: myspace
  labels:
    app: frontend-todo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: web
  selector:
    app: frontend-todo

