apiVersion: v1
kind: Service
metadata:
  name: frontend-todo
  namespace: myspace
  labels:
    app: frontend-todo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: web
  selector:
    app: frontend-todo

kind: Service
metadata:
  name: frontend-nodeport
  namespace: myspace
spec:
  type: NodePort
  ports:
  - name: nodeport
    port: 8080
    nodePort: 30081
  selector:
    app: frontend-todo
