
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-dployment
  namespace: {{ .values.space }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .values.image.name }}:{{ .values.image.version }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: {{ .values.port }}
          name: http
          protocol: TCP
        ENV:
        - name: POSTGRES_USER
          value: {{ .values.database.default.user}}
        - name: POSTGRES_PASSWORD
          value: {{ .values.database.default.password}}
        - name: POSTGRES_DB
          value: {{ .values.database.default.name}}