apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: myspace
  labels:
    app: postgres
spec:
  ports:
  - name: http
    port: 5432
    targetPort: http
  selector:
    app: postgres
 
kind: Service
metadata:
  name: postgres-port
  namespace: myspace
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    nodePort: 30432
  selector:
    app: postgres