apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: myspace
data:
  .dockerconfigjson: base64({"auths": {"server(example ghcr.io)": {"auth": "base64($username:$token)"}}})
type: kubernetes.io/dockerconfigjson

