apiVersion: v1
kind: Service
metadata:
  name: backend-todo
  namespace: myspace
  labels:
    app: backend-todo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: backend-todo

kind: Service
metadata:
  name: backend-nodeport
  namespace: myspace
spec:
  type: NodePort
  ports:
  - name: nodeport
    port: 8080
    nodePort: 30080
  selector:
    app: backend-todo